version: "3.3"

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: poatransporte
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"

